/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1edd;

import java.awt.Container;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author otto
 */
public class DisenoCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form DisenoCatalogo
     */
  /*  public String img1="";
    public String img2="";
    public String img3="";
  */  
    
    public Jugador jugador;
    public ListaPersonajes raizLp;
    
    
    public ImageIcon img1;//= new ImageIcon("C:\\eddPractica1\\Img\\Plants1.jpg");
    public ImageIcon img2;//= new ImageIcon("C:\\eddPractica1\\Img\\Plants2.jpg");
    public ImageIcon img3;//= new ImageIcon("C:\\eddPractica1\\Img\\Plants3.jpg");
    
    public DisenoCatalogo() {
        initComponents();
        
    }
    
    public void intiOtrosComponentes(){
        initImages();
        InitCombos();
        this.repaint();
    }
   
    public void setJugador(Jugador j){
        this.jugador=j; 
        if(jugador.tipo){
            this.jlblTitulo.setText("Plantas \n  Jugador: "+jugador.nombre);
        }else{
            this.jlblTitulo.setText("Zombis \n  Jugador: "+jugador.nombre);
        }
    }
    
    private void initImages(){
    if(jugador.tipo){
    img1= new ImageIcon("C:\\eddPractica1\\Img\\Plants1.png");
    img2= new ImageIcon("C:\\eddPractica1\\Img\\Plants2.png");
    img3= new ImageIcon("C:\\eddPractica1\\Img\\Plants3.png");
    this.jlblTitulo.setText("Plantas \n  Jugador: "+jugador.nombre);
    }else{
    img1= new ImageIcon("C:\\eddPractica1\\Img\\Zombis1.png");
    img2= new ImageIcon("C:\\eddPractica1\\Img\\Zombis2.png");
    img3= new ImageIcon("C:\\eddPractica1\\Img\\Zombis3.png");
    this.jlblTitulo.setText("Zombis \n  Jugador: "+jugador.nombre);
    }
    
    }
    
    private void InitCombos(){
        
       //String TiposAtaque[]={"Proyectil","Directo"};
      // String Imagenes[]={"Imagen1","Imagen2","Imagen3"};
       this.jcbImagen.removeAllItems();
       this.jcbTipoAtaque.removeAllItems();
       this.jcbImagen.addItem("Imagen1");
       this.jcbImagen.addItem("Imagen2");
       this.jcbImagen.addItem("Imagen3");
       this.jcbTipoAtaque.addItem("Directo");
       this.jcbTipoAtaque.addItem("Proyectil");
    }
    
    public void actualizarPantalla(){ 
        Container temp=this.getContentPane(); 
        SwingUtilities.updateComponentTreeUI(temp);
        temp.validate();
    }
    
    public void LimpiarCampos(){
        this.jtxtCantidad.setText("");
        this.jtxtNombre.setText("");
        this.jtxtPuntosAtaque.setText("");
        this.jtxtPuntosDefensa.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtPuntosAtaque = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtPuntosDefensa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblImagen = new javax.swing.JLabel();
        jcbImagen = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jcbTipoAtaque = new javax.swing.JComboBox();
        jtxtCantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jbtnListo = new javax.swing.JButton();
        jlblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nombre");

        jLabel2.setText("Tipo Ataque");

        jLabel3.setText("P. Ataque");

        jLabel4.setText("Cantidad");

        jLabel5.setText("Imagen");

        jlblImagen.setText(" ");

        jcbImagen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbImagenActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");

        jButton3.setText("Eliminar");

        jcbTipoAtaque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });

        jLabel11.setText("P. Defensa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtPuntosDefensa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtPuntosAtaque, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jcbImagen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbTipoAtaque, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jcbTipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtPuntosAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtPuntosDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jcbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 216, 380);

        jbtnListo.setText("Listo!");
        jbtnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnListo);
        jbtnListo.setBounds(500, 400, 160, 40);

        jlblTitulo.setText("jLabel12");
        getContentPane().add(jlblTitulo);
        jlblTitulo.setBounds(40, 400, 390, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 10, 670, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbImagenActionPerformed
        // TODO add your handling code here:
//        int indx =this.jcbImagen.getSelectedIndex();
        
         switch (this.jcbImagen.getSelectedIndex()) {
            case 0: 
                this.jlblImagen.setIcon(img1);
                break;
            case 1: 
                this.jlblImagen.setIcon(img2);
                break;
            case 2: 
                this.jlblImagen.setIcon(img3);
                break;
        }
         
         this.jlblImagen.repaint();
         this.repaint();
        
    }//GEN-LAST:event_jcbImagenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling coe here:
          Personaje personaje= new Personaje();
        try{
      
        personaje.imageicon=this.jlblImagen.getIcon();
        personaje.nombre= this.jtxtNombre.getText();
        personaje.defensa= Integer.parseInt(this.jtxtPuntosDefensa.getText());
        personaje.ataque= Integer.parseInt(this.jtxtPuntosAtaque.getText());
        personaje.tipoAtaque= this.jcbTipoAtaque.getSelectedIndex();
        personaje.cantidad= Integer.parseInt(this.jtxtCantidad.getText());
       
       this.raizLp= new ListaPersonajes(jugador.tipo);
       raizLp.insertPersonaje(personaje);
         /*  for (int i=1; i==cantidad;i++){
           //Practica1Edd.CatPlantas.insertPersonaje(personaje);
           } */
        GridLayout layout = new GridLayout(0,1);
        
        personaje.setText("Nombre: "+personaje.nombre+"      P. Ataque: "+personaje.ataque+"    P. Defensa: "+personaje.defensa+"     Tipo Ataque: "+this.jcbTipoAtaque.getItemAt(personaje.tipoAtaque));
        personaje.setSize(this.jPanel3.getWidth()-10,100);
        personaje.setIcon(personaje.imageicon);
        personaje.setVisible(true);
        this.jPanel3.setLayout(layout);
        this.jPanel3.add(personaje);
        this.actualizarPantalla();
        this.LimpiarCampos();
        
        }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListoActionPerformed
        // TODO add your handling code here:
        if(this.raizLp!=null){
            if(this.raizLp.contadorPersonajes>0){
        // si hay jugadores pendientes 
        if(jugador.siguienteJ!=null){
             DisenoCatalogo dc =new DisenoCatalogo();
             dc.setSize(900,500);
             dc.setJugador(jugador.siguienteJ);
             dc.setVisible(true);
        }else{
            /*AQUI SE LLAMA AL JFORM DEL JUEGO COMO TAL*/
        }
        this.setVisible(false);
        this.dispose();
            }else{
            JOptionPane.showMessageDialog(this,"Ingrese al menos un personaje");
            }
        }else{
        JOptionPane.showMessageDialog(this,"No a ingresando personajes");
        }
    }//GEN-LAST:event_jbtnListoActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
/**/    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisenoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisenoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisenoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisenoCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   /**/     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisenoCatalogo().setVisible(true);
            }
        });
    }/**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnListo;
    private javax.swing.JComboBox jcbImagen;
    private javax.swing.JComboBox jcbTipoAtaque;
    private javax.swing.JLabel jlblImagen;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPuntosAtaque;
    private javax.swing.JTextField jtxtPuntosDefensa;
    // End of variables declaration//GEN-END:variables
}
